version: '3.2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181
  kafka1:
    image: 'wurstmeister/kafka'
    hostname: kafka1
    ports:
      - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: kafka1
  kafka2:
    image: 'wurstmeister/kafka'
    hostname: kafka2
    ports:
      - 9093:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: kafka2
  kafka3:
    image: 'wurstmeister/kafka'
    hostname: kafka3
    ports:
      - 9094:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: kafka3

